$do_certs_update = <<-'SCRIPT'
echo "#################################################Copy SSL Root Certificate (Ubuntu)#################################################"
sudo cp /vagrant/ZscalerRootCertificate.crt /usr/local/share/ca-certificates
sudo update-ca-certificates --fresh
sudo apt-get update
echo "#################################################CA Certificates Refreshed#################################################"
SCRIPT

ssh_pub_key = File.readlines("#{Dir.home}/.ssh/chef-workstation.pub").first.strip

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"

  config.hostmanager.enabled           = true
  config.hostmanager.manage_host       = true
  config.hostmanager.manage_guest      = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline   = true
  
  (1..4).each do |i|
    config.vm.define "web#{i}" do |node|
      node.vm.hostname ="web#{i}"
      node.vm.network "private_network", ip:"192.168.1.#{50+i}"
      node.vm.provider 'virtualbox' do |vm|
        vm.name = "web#{i}"
      end
    end   
  end
  (1..2).each do |i|
    config.vm.define "lb#{i}" do |node|
      node.vm.hostname ="lb#{i}"
      node.vm.network "private_network", ip:"192.168.1.#{60+i}"
      node.vm.provider 'virtualbox' do |vm|
        vm.name = "lb#{i}"
      end
    end
  end

  if ARGV[0] != 'destroy'
    config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
  end

  config.vm.synced_folder "../shared/", "/vagrant"
  config.vm.provision "shell", inline: $do_certs_update
end


