Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"

  config.vm.define "workstation" do |node|
    node.vm.hostname ="workstation"
    node.vm.network "private_network", ip:"192.168.1.10"
    config.vm.provider 'virtualbox' do |vm|
      vm.name = "workstation"
    end
    
    config.vm.synced_folder "../shared/", "/vagrant"
    config.vm.synced_folder "../workspace/", "/home/vagrant/chef-starter"
    config.vm.provision "shell", path: "../scripts/update-ssl-certs.sh"
    config.vm.provision "shell", path: "../scripts/install-chef-workstation.sh"
  end
end
