### WORK IN PROGRESS
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"
  config.vm.hostname ="chef-server-local"
  config.vm.network "private_network", ip:"172.28.128.20"
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '5000'
    vb.name = "chef-server-local"
  end
  config.vm.provision "shell", inline: $script
end
### WORK IN PROGRESS